
# This is a basic workflow to help you get started with Actions
name: DeploySampleApp
env:
  RESOURCE_GROUP: 'aksrunners-rg'
  CLUSTER_NAME: 'aksrunners-aks'
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - 'sampleapp/**' 
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout source code 
      uses: actions/checkout@v3
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
